server:
  port: 8040
spring:
  data:
    mongodb:
      username: sen
      password: sen
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.sen.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.sen.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: 127.0.0.1
    port: 1025
    username: sen
    password: sen
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
management:
  tracing:
    sampling:
      probability: 1.0