spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/micro-servies
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: gateway-service
