#spring:
#  application:
#    name: discovery-service
#  config:
#    import: optional:configserver:http://config-server:8888
server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: 'OFF'