#spring:
#  application:
#    name: customer-service
#  data:
#    mongodb:
#      username: sen
#      password: sen
#      database: customer
#      host: localhost
#      port: 27017
#      authentication-database: admin
#server:
#  port: 8090
spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: customer-service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
#management:
#  tracing:
#    sampling:
#      probability: 1.0